### ISSUE TITLE
Is there Res2Net50 pretrained checkpoint for DIS5k dataset?

### ISSUE THREAD

**Issue by jiamingNo1** [plemeri/InSPyReNet#19]
Hi, I see that the model zoo doesn't have Res2Net50 pretrained checkpoint except for DUTS dataset. 
Or can you provide relevant training configurations?

**Comment by plemeri** [comment]
Hello, we did not trained Res2Net50 backbone model for high-resolution datasets.
However, you can train the model by changing the configuration `Model.name` as `InSPyReNet_Res2Net50` instead of `InSPyReNet_SwinB`.

Also, for high-resolution training, change `Model.base_size` and `Train.Dataset.transforms.static_resize.size` as `[1024, 1024]` instead of `[384, 384]`for larger input size. Don't forget to change datasets by changing `Train.Dataset.sets`. 

Lastly, for high-resolution inference, change `Test.Dataset.transforms.static_resize.size` as `[1024, 1024]`, or use `dynamic_resize` with `L: 1280`. 

For more information, please refer to [getting started / train & evaluate](https://github.com/plemeri/InSPyReNet/blob/main/docs/getting_started.md#train--evaluate).

**Comment by jiamingNo1** [comment]
Thank you~
