### ISSUE TITLE
Empty mBA result for PASCAL-S dataset

### ISSUE THREAD

**Issue by moktsuiqin** [plemeri/InSPyReNet#22]
Hi, can I know what is the reason of being NaN for mBA result only in PASCAL-S dataset?

**Comment by moktsuiqin** [comment]
![Screenshot 2023-03-24 074352](https://user-images.githubusercontent.com/81372023/227388353-fc71296d-2eb6-4956-8052-f23f55d44fbb.jpg)

**Comment by plemeri** [comment]
First of all, bounday accuracy (mBA) is not designed for Low Resolution datasets (DUTS-TE, DUT-OMRON, ECSSD, HKU-IS, PASCAL-S). Second, unlike other datasets, PASCAL-S has multiple values other than 255 according to each object's saliency. In other words, while other datasets are labeled either 0 or 255 for each pixel, PASCAL-S has multiple values including 0 and 255 such as 128.

Long story short, because of such difference, mBA shows NaN.
Thanks

**Comment by moktsuiqin** [comment]
Thank you so much for your answer
