### ISSUE TITLE
Model accuracy drops after a few epoch when training with custom dataset !

### ISSUE THREAD

**Issue by ds-jpg** [plemeri/InSPyReNet#27]
Hi @plemeri 

Thank you for your work. 

I tried training the swin b model from scratch with my custom dataset which is having 420000 images of humans , products , cars . etc (210000 * 2 Horizontal Flip ) , after a few epoch of training it starts giving weird output and the accuracy drops and the output from the model becomes very poor. 

I had changed the batch size to 8 in order to train the model little quicker but the results started to get very horrible after a few epochs. Can you please tell me why this is occurring ? 

Please see the attached input and output images for a better understanding of the problem. 
[image-compare.pdf](https://github.com/plemeri/InSPyReNet/files/11214837/image-compare.pdf)

Thanks :)

**Comment by plemeri** [comment]
Hello @ds-jpg

First of all, by just seeing the results cannot tell the problem exactly.
But I think the issue came from the training and inference image size difference.

I recommend using another configuration which we used for real-world scenario with composite datasets.
[Plus_Ultra.yaml](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra.yaml) 

Thank you.
