### ISSUE TITLE
Image mask alignment problem

### ISSUE THREAD

**Issue by babyta** [plemeri/InSPyReNet#39]
Hello author, for a recent test, I wrote an inference script myself, but the inference results between threshold value 512 and None seem to be 1-2 pixels different.

**Comment by babyta** [comment]
![512](https://github.com/plemeri/InSPyReNet/assets/37787795/a3712c13-f808-471e-a4c3-94827f4bd0cf)
The picture above shows the result of threshold 512
![None](https://github.com/plemeri/InSPyReNet/assets/37787795/d1c42840-53fe-4691-9404-2946dcf4315f)
The picture above shows the result of threshold None
Focusing on the edges of the image, you can see that they are not aligned

**Comment by xkaple00** [comment]
I also noticed such behavior. In my experiments if I do inference on images larger than 512 px with --threshold parameter = 512, the produced mask is shifted a few pixels up and left in comparison with --threshold=None

**Comment by plemeri** [comment]
Hi @babyta and @xkaple00, if `threshold` is specified, images with shorter side length (either width or height) below the `threshold` value will not deploy pyramid blending. On the other hand, if `threshold` value is not specified (None), then it will not deploy pyramid blending what so ever. 

Also, because pyramid blending is a post-processing method combining LR and HR predictions into single mask, there could be some drawbacks like 1~2 pixel shift. 

Please notice that pyramid blending will produce meaningful results only when the given image is high resolution, because pyramid blending is proposed to produce high resolution prediction when without high resolution dataset available. It is obvious when high resolution dataset is available, we definitely need to use them for high quality prediction. One of our contributions was, even without costly high resolution dataset, we were able to generate competitive high quality saliency map with pyramid blending technique.

Also, if you want to use our method in real-world scenario, please use [Plus_Ultra](https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md#-trained-with-massive-sod-datasets-with-lr-384-x-384-and-hr-1024-x-1024-not-in-the-paper-for-real-world-scenarios) configuration, or our python API / cli tool [transparent-background](https://github.com/plemeri/transparent-background). 

Lastly, if you have an idea to solve the problem, please contact me or you can create a pull request.
Thank you for letting me know such problem. 😄

**Comment by babyta** [comment]
Thank you for your reply, your sharing is very useful！
